- name: Clean old file
  run: rm -f dashboard.json

- name: Build dashboard
  run: python scripts/build_dashboard.py

- name: Show output
  run: cat dashboard.json

- name: Deploy
  run: |
    curl -X POST https://api.us1.signalfx.com/v2/dashboard \
    -H "Content-Type: application/json" \
    -H "X-SF-TOKEN: ${{ secrets.SPLUNK_TOKEN }}" \
    -d @dashboard.json
